version: '3.8'
services:
  db:
    image: postgres:14
    container_name: alfa_api_db
    environment:
      POSTGRES_USER: alfa_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: alfa_api
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: alfa_api
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: alfa_user
      DATABASE_PASSWORD: password
      DATABASE_NAME: alfa_api
    depends_on:
      - db

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  db_data:
